# Generated by Django 4.1.7 on 2023-05-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_account_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
