# Generated by Django 4.1.7 on 2023-05-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
