# Generated by Django 4.1.7 on 2023-06-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_transaction_owner_alter_transaction_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.FloatField(),
        ),
    ]
